SET(EXTERNAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/External")

#add glew find paths
LIST(APPEND CMAKE_INCLUDE_PATH "${EXTERNAL_PATH}/glew/include")
IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
	LIST(APPEND CMAKE_LIBRARY_PATH "${EXTERNAL_PATH}/glew/lib/Release/x64")
ELSE()
	LIST(APPEND CMAKE_LIBRARY_PATH "${EXTERNAL_PATH}/glew/lib/Release/Win32")
ENDIF()
#add opengl find path
LIST(APPEND CMAKE_INCLUDE_PATH "${EXTERNAL_PATH}/OpenGL")
#add egl
LIST(APPEND CMAKE_LIBRARY_PATH "${EXTERNAL_PATH}/egl/x64")
#add glm
LIST(APPEND CMAKE_INCLUDE_PATH "${EXTERNAL_PATH}/glm")